### ISSUE TITLE
[Client/Server] Cyr not working

### ISSUE THREAD

**Issue by a-rmz** [a-rmz/JEasyCrypto#7]
## Description
**Cyr** encryption works on console but fails in Client/Server.

## Steps to Reproduce the Problem

  1. Send a message cyphered with cyr through the client.
  2. :boom: 

## Expected Behavior
Get the proper encrypted/decrypted message.

## Reproduces how often: [What percentage of the time does it reproduce?]
Every time.

## Additional info
Related to #8.

**Comment by risju62** [comment]
How does this actually manifest? In Windows 7 it does not crash as the description seems to suggest. The returned string is all question marks.

**Comment by anttijuu** [comment]
Issue is related to 14, and is about Unicode characters. Supported characters and default charsets may differ across machines, operating systems. So the issue may not appear on single machine which is using a single default set of characters. Cyr method returns text so that it translates basic latin character range to the Cyrillian range. Cyrillian may not display on all environments (and/or consoles) if environment do not support it as-is (may support if prepared for it and/or code takes this into account). In this case only question marks are displayed. See e.g. http://stn.audible.com/abcs-of-unicode/ and https://unicode-table.com/en/#basic-latin This is a very important matter in creating software for global markets.

**Comment by risju62** [comment]
Does not seem work on windows:
Starting to receive responses...
2
Give encryption method > cyr
Give text to encrypt > jippii kissa puussa
Welcome to CryptoClient!
Select command (1-4):
 1: Send capability request to service
 2: Send encrypt request to service
 3: Send decrypt request to service
 4: Quit application
Response received.
Your choice > Received raw data: {"result":0,"data":"???????????????????","id":4,"operation":"encrypt-response"}
Parsing...

**Comment by a-rmz** [comment]
@dtoniuc, can you please help with this one?

**Comment by risju62** [comment]
Hmm, cyr does not work on console either, so you can forget my comment. The fix is probably working ok on client/server.

**Comment by dtoniuc** [comment]
I can try to help but is not clear for me how the problem manifest itself.

**Comment by risju62** [comment]
The encrypted message appears as all question marks.

**Comment by dtoniuc** [comment]
I will have this issue checked, however I think that the problem might not be from the code but from the fact that the font used in windows cmd is not able to display Cyrillic characters

**Comment by ChouaibHamek** [comment]
Not being able to correctly see the characters on Windows is irrelevant to this issue:
1 - This problem happens also when you run cry on the console. 
2 - What have provided a fix for the client/server cry problem. The core problem of this issue was a mismatch between the length of the string passed before and after calling getBytes()  - Fixing the length mismatch problem solved the issue. The second commit where we explicitly added a standardized encoding (StandardCharsets.UTF_16) across the server and client was an additional preventive step in case the client and server ran on different platforms that have different default charsets.
3 - I think this issue should be closed. The problem of platforms charset incompatibility should be dealt with in another issues.

**Comment by anttijuu** [comment]
"The problem of platforms charset incompatibility should be dealt with in another issues." True. There is the issue "User interface"  #16 , which means the Client -- there is a need for GUI anyways, so getting rid of the console by using a GUI would solve this problem.

**Comment by a-rmz** [comment]
So, @dtoniuc @ChouaibHamek, we consider that the "new" issue (not displaying the chars) is a Windows problem and this issue is no more valid since the original problem is fixed? And the work to be done on #16 will fix the whole thing. Agree?

**Comment by ChouaibHamek** [comment]
Yes, exactly.
